# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b09285216e9c94ae64dc670fc84a4f347a62097fba3be8f3a7c2fa1e688c024f0ceffc3995fa611636592fd96db0a8844ffe9cf02406d771be89462d2a5624e1

test:
  secret_key_base: de2249584a10b39830fbe3e8daf50bd74af36cadc052264011032b9d790cdc557bf90f5f5a2f3107b926a008f7d65b245c2d22cf5d54e4f9f62c86902be4b0fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
